# NIQuery base container
FROM nicholsn/ansible:latest
MAINTAINER Nolan Nichols <nolan.nichols@gmail.com>

RUN apt-get update 
RUN apt-get install -y git-core
#RUN ansible-pull -C master -d /opt -i provisioning/hosts -U https://github.com/niquery/niquery.git provisioning/base.yml
