---
# Tasks for niquery role

- name: Checkout niquery app into webapps_dir directory
  git: repo=https://github.com/niquery/niquery.git dest={{ webapps_dir }}/{{ app_name }}
  
- name: include supervisor.ini for niquery app
  template: src=supervisor.ini.j2 dest=/etc/supervisor/niquery.ini
  notify: restart supervisord
